services:
  node:
    image: node:18-alpine
    depends_on: [minio]
    command: /app/test.mjs
    volumes:
      - .:/app
      - ./aws-config:/root/.aws/config
      - ./aws-credentials:/root/.aws/credentials

  php:
    image: php:8.3-cli-alpine
    depends_on: [minio]
    command: /app/test.php
    volumes:
      - .:/app
      - ./aws-config:/root/.aws/config
      - ./aws-credentials:/root/.aws/credentials

  awscli:
    image: amazon/aws-cli
    environment:
      AWS_ENDPOINT_URL: http://minio:9001

  minio:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/test-bucket && minio server /data --address :9000 --console-address :9001'
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
